To pull request
ncedu-tlt/2020-impl-class-register pull request #4
Opened 2021-01-26 14:41 UTC by OlegPozhenskij

Ready for review

2021-01-26 15:29 UTC, OlegPozhenskij commented on server/src/main/java/com/pozhenskii/springjwt/controllers/TestController.java
> +		userRepository.save(user);
Забыл сделать возврат request'а со различными статусами, сделаю

2021-01-27 11:12 UTC, alexfoxrussian requested changes

2021-01-27 11:12 UTC, alexfoxrussian commented on client/src/App.vue
> +    <nav class="navbar navbar-expand navbar-dark bg-dark">
Navigation Bar в отдельный компонент вынести надо

2021-01-27 11:12 UTC, alexfoxrussian commented on client/src/services/user.service.js
> +const API_URL = 'http://localhost:8080/api/test/';
API_URL - локалхост надо поменять

2021-01-27 11:12 UTC, alexfoxrussian commented on server/src/main/java/com/pozhenskii/springjwt/SpringBootSecurityJwtApplication.java
> +package com.pozhenskii.springjwt;
переименуй pozhenskii в classregister везде

2021-01-27 14:29 UTC, dnsonin commented on server/src/main/java/com/pozhenskii/springjwt/SpringBootSecurityJwtApplication.java
> +package com.pozhenskii.springjwt;
package com.netcracker.ncedu.tlt.impl.class_register;

2021-01-27 15:33 UTC, dnsonin commented on client/src/services/user.service.js
> +const API_URL = 'http://localhost:8080/api/test/';
/api/test/ - здесь 
в остальных URL так же: используй относительный путь.

2021-01-29 10:17 UTC, alexfoxrussian requested changes
![image](https://user-images.githubusercontent.com/6068138/106262471-81ca2300-623c-11eb-9145-48209527cbbe.png)
зачем в МР добавил удаление презентаций?

2021-01-29 10:17 UTC, alexfoxrussian commented on client/src/router.js
> +      path: '/findStudent',
в URL не используют camelCase. либо все маленькие буквы, либо kebab-case.

2021-01-29 10:17 UTC, alexfoxrussian commented on client/src/router.js
> +      path: '/passWord',
аналогично (либо маленькие буквы, либо kebab-case) хотя в данном случае - маленькие буквы.

2021-01-29 10:17 UTC, alexfoxrussian commented on client/src/router.js
> +      component: () => import('./views/Billboard.vue')
Определись, либо lazy-loading, либо нет. Зачем дублируешь руты?

2021-01-29 10:17 UTC, alexfoxrussian commented on client/src/router.js
> +      component: () => import('./views/FindStudent.vue')
аналогично верхнему

2021-01-29 10:17 UTC, alexfoxrussian commented on client/src/router.js
> +      component: () => import('./views/PassWord.vue')
аналогично верхнему замечанию.
+ password - это одно слово и camelCase'ом не пишется. (поправь везде)

2021-01-29 10:34 UTC, OlegPozhenskij commented on client/src/router.js
> +      path: '/findStudent',
Исправил

2021-01-29 10:34 UTC, OlegPozhenskij commented on client/src/router.js
> +      path: '/passWord',
Исправил

2021-01-29 10:34 UTC, OlegPozhenskij commented on client/src/router.js
> +      component: () => import('./views/Billboard.vue')
Видимо хотел убрать позже, исправил

2021-01-29 10:34 UTC, OlegPozhenskij commented on client/src/router.js
> +      component: () => import('./views/FindStudent.vue')
Исправил

2021-01-29 10:34 UTC, OlegPozhenskij commented on client/src/router.js
> +      component: () => import('./views/PassWord.vue')
Исправил

2021-01-29 12:29 UTC, dnsonin approved these changes
Не вижу изменений в бэк-энде, OK.

2021-01-29 12:40 UTC, alexfoxrussian approved these changes

2021-01-29 13:28 UTC, merged